### ISSUE TITLE
S&box

### ISSUE THREAD

**Issue by SryEyes** [anarh1st47/Source2Dumps#3]
ayo

got some dumps of the game s&box wich also uses s2
Do you need the normal netvar dump or the whole schemasystem dump ?

greetings

**Comment by anarh1st47** [comment]
> ayo
> 
> got some dumps of the game s&box wich also uses s2 Do you need the normal netvar dump or the whole schemasystem dump ?
> 
> greetings

Hello, would be nice if you can share schema dump or any other info

**Comment by anarh1st47** [comment]
Provided via #4, thanks
